services:
  webapp:
    tty: true
    build: .
    ports:
      - "8080:8080"
      - "8025:8025"
    volumes:
      - type: bind
        source: ./src/main/target
        target: /target
volumes:
  webapp: